---
- name: Download rbenv repository
  git: >
   repo=https://github.com/sstephenson/rbenv.git
   dest=/home/vagrant/.rbenv/

- name: Download ruby-build repository
  git: >
   repo=https://github.com/sstephenson/ruby-build.git
   dest=/home/vagrant/.rbenv/plugins/ruby-build/

- name: Set dir config
  file: path=/home/vagrant/.rbenv owner=vagrant state=directory recurse=yes

- name: Set rbenv bin path
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> /home/vagrant/.bashrc
  become: no

- name: Set rbenv shims path
  shell: echo 'export PATH="$HOME/.rbenv/shims:$PATH"' >> /home/vagrant/.bashrc
  become: no

- name: Set rbenv init path
  shell: echo 'eval "$(rbenv init -)"' >> /home/vagrant/.bashrc
  become: no

- name: Install ruby
  shell: bash -lc "rbenv install -v {{ ruby_version }}"
  become: no

- name: rbenv rehash
  shell: bash -lc "rbenv rehash"
  become: no

- name: Set ruby global version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  become: no

- name: Install bundler
  shell: bash -lc "gem install bundler"
  become: no
