<template>
    <div>
        <nav>
            <ul>
                <li>
                    <a>Home</a>
                </li>
            </ul>
        </nav>
        <router-view></router-view>
    </div>
</template>
