version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: cd ./src/backend-app && cp .env.example .env && cat .env
      - run: docker exec -it rubel_php /bin/sh -c "cd backend-app/ && composer install && php artisan key:generate && php artisan migrate && php artisan db:seed"
      - run: docker exec -it rubel_php /bin/sh -c "cd backend-app/ && composer test"
      - run: docker exec -it rubel_php /bin/sh -c "cd backend-app/ && npm cache verify && npm install && npm run install"
      - run: docker exec -it rubel_php /bin/sh -c "cd frontend-app/ && npm cache verify && npm install && npm run install"
      - restore_cache:
          keys:
            - v1-composer-dependencies-{{ checksum "./src/backend-app/composer.lock" }}
            - v1-composer-dependencies-
      - save_cache:
          paths:
            - ./src/backend-app/vendor
          key: v1-composer-dependencies-{{ checksum "./src/backend-app/composer.lock" }}
