version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: cd ./src/client-app && cp .env.example .env
      - run: docker exec -it rubel_php /bin/sh -c "cd client-app/ && composer install"
      - run: docker exec -it rubel_php /bin/sh -c "cd client-app/ && npm cache verify && npm install && npm run build"
      - run: docker exec -it rubel_php /bin/sh -c "cd admin-app/ && npm cache verify && npm install && npm run build"
      - run: docker exec -it rubel_php /bin/sh -c "cd client-app/ && php artisan key:generate"
      - run: docker exec -it rubel_php /bin/sh -c "cd client-app/ && php artisan migrate && php artisan db:seed"
      - run: docker exec -it rubel_php /bin/sh -c "cd client-app/ && composer test"
