version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker exec -it rubel_php -c "cd backend-app/ && composer install && php artisan migrate && php arisan db:seed"
      - run: docker exec -it rubel_php -c "cd backend-app/ && composer test"
      - run: docker exec -it rubel_php -c "cd backend-app/ && npm cache verify && npm install && npm run install"
      - run: docker exec -it rubel_php -c "cd frontend-app/ && npm cache verify && npm install && npm run install"
      - restore_cache:
          keys:
            - v1-composer-dependencies-{{ checksum "./src/backend-app/composer.lock" }}
            - v1-composer-dependencies-
      - run: cd ./src/backend-app; composer install --prefer-dist; php artisan key:generate
      - save_cache:
          paths:
            - ./src/backend-app/vendor
          key: v1-composer-dependencies-{{ checksum "./src/backend-app/composer.lock" }}
