version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - run: sudo apt-get install -y nodejs npm
      - run: sudo npm cache clean
      - run: sudo npm install n -g
      - run: sudo n stable
      - run: sudo ln -sf /usr/local/bin/node /usr/bin/node
      - run:
          name: Print system information
          command: |
            echo "node $(node -v)"
            echo "npm v$(npm --version)"
            echo "php $(php -v)"
      - run: cd backend-app; cp .env.example .env
      - restore_cache:
          keys:
            - v1-composer-dependencies-{{ checksum "backend-app/composer.lock" }}
            - v1-composer-dependencies-
      - run: cd backend-app; composer install --prefer-dist; php artisan key:generate
      - save_cache:
          paths:
            - ./backend-app/vendor
          key: v1-composer-dependencies-{{ checksum "backend-app/composer.lock" }}
      - run: cd backend-app; npm run refresh
      - run: cd frontend-app; npm run refresh
      - run: cd backend-app; ./vendor/bin/phpunit
