---
- name: Add repository
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm state=present

- name: Install mysql
  yum: name=mysql-community-server

- name: Install MySQL-python
  yum: name=MySQL-python

- name: Run mysql
  service: name=mysqld state=started enabled=yes

- name: Set the my.cnf
  template:
    src: ../templates/.my.cnf.j2
    dest: "/root/.my.cnf"
    mode: 0600

- name: Set the password for root
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
