---
- name: Download pyenv repository
  git: >
   repo=https://github.com/yyuu/pyenv.git
   dest=/home/vagrant/.pyenv/

- name: Set dir config
  file: path=/home/vagrant/.pyenv owner=vagrant state=directory recurse=yes

- name: Set pyenv path
  shell: echo 'export PYENV_ROOT="$HOME/.pyenv"' >> /home/vagrant/.bashrc

- name: Set pyenv bin path
  shell: echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> /home/vagrant/.bashrc
  become: no

- name: Set pyenv init path
  shell: echo 'eval "$(pyenv init -)"' >> /home/vagrant/.bashrc
  become: no

- name: Install python
  shell: bash -lc "pyenv install -v {{ python_version }}"
  become: no

- name: pyenv rehash
  shell: bash -lc "pyenv rehash"
  become: no

- name: Set python global version
  shell: bash -lc "pyenv global {{ python_version }}"
  become: no
